/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NateNavBar {
        "isMainMenuOpen": boolean;
        "isNestListItemOpen": boolean;
    }
    interface NiAboutUsCard {
        "cardDescription": string;
        "cardTitle": string;
        "image": string;
        "link": string;
    }
    interface NiBlogCard {
        "blogTitle": string;
        "date": string;
        "imageSource": string;
        "link": string;
    }
    interface NiCarouselCard {
        "numberStars": number;
        "siteLogo": string;
    }
    interface NiNavBarBoot {
    }
    interface NiReviewBox {
    }
    interface NiReviewContainer {
        "firstName": string;
        "lastName": string;
        "profileImage": string;
        "rating": number;
        "reviewText": string;
        "siteLogo": string;
    }
}
declare global {
    interface HTMLNateNavBarElement extends Components.NateNavBar, HTMLStencilElement {
    }
    var HTMLNateNavBarElement: {
        prototype: HTMLNateNavBarElement;
        new (): HTMLNateNavBarElement;
    };
    interface HTMLNiAboutUsCardElement extends Components.NiAboutUsCard, HTMLStencilElement {
    }
    var HTMLNiAboutUsCardElement: {
        prototype: HTMLNiAboutUsCardElement;
        new (): HTMLNiAboutUsCardElement;
    };
    interface HTMLNiBlogCardElement extends Components.NiBlogCard, HTMLStencilElement {
    }
    var HTMLNiBlogCardElement: {
        prototype: HTMLNiBlogCardElement;
        new (): HTMLNiBlogCardElement;
    };
    interface HTMLNiCarouselCardElement extends Components.NiCarouselCard, HTMLStencilElement {
    }
    var HTMLNiCarouselCardElement: {
        prototype: HTMLNiCarouselCardElement;
        new (): HTMLNiCarouselCardElement;
    };
    interface HTMLNiNavBarBootElement extends Components.NiNavBarBoot, HTMLStencilElement {
    }
    var HTMLNiNavBarBootElement: {
        prototype: HTMLNiNavBarBootElement;
        new (): HTMLNiNavBarBootElement;
    };
    interface HTMLNiReviewBoxElement extends Components.NiReviewBox, HTMLStencilElement {
    }
    var HTMLNiReviewBoxElement: {
        prototype: HTMLNiReviewBoxElement;
        new (): HTMLNiReviewBoxElement;
    };
    interface HTMLNiReviewContainerElement extends Components.NiReviewContainer, HTMLStencilElement {
    }
    var HTMLNiReviewContainerElement: {
        prototype: HTMLNiReviewContainerElement;
        new (): HTMLNiReviewContainerElement;
    };
    interface HTMLElementTagNameMap {
        "nate-nav-bar": HTMLNateNavBarElement;
        "ni-about-us-card": HTMLNiAboutUsCardElement;
        "ni-blog-card": HTMLNiBlogCardElement;
        "ni-carousel-card": HTMLNiCarouselCardElement;
        "ni-nav-bar-boot": HTMLNiNavBarBootElement;
        "ni-review-box": HTMLNiReviewBoxElement;
        "ni-review-container": HTMLNiReviewContainerElement;
    }
}
declare namespace LocalJSX {
    interface NateNavBar {
        "isMainMenuOpen"?: boolean;
        "isNestListItemOpen"?: boolean;
    }
    interface NiAboutUsCard {
        "cardDescription"?: string;
        "cardTitle"?: string;
        "image"?: string;
        "link"?: string;
    }
    interface NiBlogCard {
        "blogTitle"?: string;
        "date"?: string;
        "imageSource"?: string;
        "link"?: string;
    }
    interface NiCarouselCard {
        "numberStars"?: number;
        "siteLogo"?: string;
    }
    interface NiNavBarBoot {
    }
    interface NiReviewBox {
    }
    interface NiReviewContainer {
        "firstName"?: string;
        "lastName"?: string;
        "profileImage"?: string;
        "rating"?: number;
        "reviewText"?: string;
        "siteLogo"?: string;
    }
    interface IntrinsicElements {
        "nate-nav-bar": NateNavBar;
        "ni-about-us-card": NiAboutUsCard;
        "ni-blog-card": NiBlogCard;
        "ni-carousel-card": NiCarouselCard;
        "ni-nav-bar-boot": NiNavBarBoot;
        "ni-review-box": NiReviewBox;
        "ni-review-container": NiReviewContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nate-nav-bar": LocalJSX.NateNavBar & JSXBase.HTMLAttributes<HTMLNateNavBarElement>;
            "ni-about-us-card": LocalJSX.NiAboutUsCard & JSXBase.HTMLAttributes<HTMLNiAboutUsCardElement>;
            "ni-blog-card": LocalJSX.NiBlogCard & JSXBase.HTMLAttributes<HTMLNiBlogCardElement>;
            "ni-carousel-card": LocalJSX.NiCarouselCard & JSXBase.HTMLAttributes<HTMLNiCarouselCardElement>;
            "ni-nav-bar-boot": LocalJSX.NiNavBarBoot & JSXBase.HTMLAttributes<HTMLNiNavBarBootElement>;
            "ni-review-box": LocalJSX.NiReviewBox & JSXBase.HTMLAttributes<HTMLNiReviewBoxElement>;
            "ni-review-container": LocalJSX.NiReviewContainer & JSXBase.HTMLAttributes<HTMLNiReviewContainerElement>;
        }
    }
}
